# Generated by Django 3.1.3 on 2020-11-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='PICTURE/no-photo-available.png', height_field=100, upload_to='PICTURE', width_field=100),
        ),
    ]
