# Generated by Django 3.1.3 on 2020-11-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201122_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='name',
            new_name='picture_name',
        ),
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='PICTURE/no-photo-available.png', height_field=100, upload_to='PICTURE/', verbose_name='Picture Photo', width_field=100),
        ),
    ]
