# Generated by Django 3.1.3 on 2020-11-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201122_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='PICTURE/no-photo-available.png', height_field='100', upload_to='PICTURE/', verbose_name='Picture Photo', width_field='100'),
        ),
    ]
