# Generated by Django 3.1.3 on 2020-11-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201122_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(default='media/pICTURE/no-photo-available.png', help_text='150x150px', upload_to='PICTURE/', verbose_name='Picture Photo'),
        ),
    ]
